FROM tezos/tezos:((tezos_version))
RUN sudo apk add jq curl supervisor
COPY supervisord-tezos.conf /etc/supervisord-tezos.conf
COPY tezos-baker.sh /
COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD []
