#!/bin/sh

# First, check that the remote signer is reachable

source /etc/tezos-signer-checker-params
echo "$3:$4 Livelessness check 1: Probing for liveness of the remote signer at http://$3:$4/$PUBLIC_BAKING_KEY"
if /usr/local/bin/tezos-client --protocol $PROTOCOL_SHORT -d /var/run/tezos/client -c /var/run/tezos/client/config import secret key k8s-baker "http://$3:$4/$PUBLIC_BAKING_KEY" -f; then
    echo "$3:$4 Livelessness check 1 passed"
else
    echo "$3:$4 Livelessness check 1 failed"
    exit 1
fi

# do not perform second check for now, it doesn't really work well
exit 0

echo "$3:$4 Livelessness check 2: Check that the Ledger is connected, has baking app open and is registered to bake for this key"
if /usr/bin/ssh -i /home/tezos/.ssh/id_rsa -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $(( $4 + 1000)) tezos@localhost; then
    echo "$3:$4 Livelessness check 2 passed"
else
    echo "$3:$4 Livelessness check 2 failed"
    exit 1
fi
